server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/auth/ {
        proxy_pass http://auth-api-service.staging.svc.cluster.local/api/auth/;
    }

    location /api/Student/ {
        proxy_pass http://student-api-service.staging.svc.cluster.local/api/Student/;
    }

    location /api/reports/ {
        proxy_pass http://reporting-service.staging.svc.cluster.local:8000/api/reports/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
