apiVersion: v1
kind: Service
metadata:
  name: course-frontend-service
  annotations:
    service.beta.kubernetes.io/azure-pip-name: prod-frontend-ip2
    service.beta.kubernetes.io/azure-load-balancer-resource-group: fullstack-production-cluster_group
spec:
  type: LoadBalancer
  selector:
    app: course-frontend
  ports:
    - port: 80
      targetPort: 80