apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-api
  labels:
    app: course-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-api
  template:
    metadata:
      labels:
        app: course-api
    spec:
      containers:
      - name: course-api
        image: fullstackregistry.azurecr.io/course-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: course-api-service
spec:
  selector:
    app: course-api
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

