apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
      - name: reporting-service
        image: fullstackregistry.azurecr.io/reporting-service:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-service  
spec:
  selector:
    app: reporting-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
