server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/course/ {
        proxy_pass http://course-api-service.staging.svc.cluster.local/api/course/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
